{% set name = "Bonsu" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a9ad74dba57986b7c9b1a57cedc85f49e7450685abffd366bbbf007354d5d88

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --global-option=build_ext --global-option=-I$PREFIX/include
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libXxf86vm') }}  # [linux]
    - {{ cdt('mesa-libgl') }}  # [linux]
  host:
    - pip
    - setuptools
    - python
    - pillow
    - wxpython
    - vtk
    - hdf5
    - h5py
    - numpy
    - fftw
  run:
    - python
    - pillow
    - wxpython
    - vtk
    - hdf5
    - h5py
    - numpy
    - fftw

test:
  imports:
    - bonsu
    - bonsu.docs
    - bonsu.image
    - bonsu.interface
    - bonsu.lib
    - bonsu.operations
    - bonsu.phasing
    - bonsu.sequences

about:
  home: https://github.com/bonsudev/bonsu
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: bonsu/licence/gpl.txt
  summary: Bonsu - The Interactive Phase Retrieval Suite

extra:
  recipe-maintainers:
    - anthchirp
